# Generated by Django 3.2.8 on 2021-11-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wru', '0003_entry_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='url',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
