# Generated by Django 3.2.8 on 2021-11-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wru', '0004_auto_20211104_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeling',
            name='icon',
            field=models.CharField(default='<i class="las la-question-circle"></i>', max_length=100, unique=True),
        ),
    ]
