# Generated by Django 3.2.8 on 2021-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wru', '0006_auto_20211106_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
